apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-secrets
    creationPolicy: Owner
    template:
      data:
        admin-user: "{{ .admin_user }}"
        admin-password: "{{ .admin_password }}"
        postgres-password: "{{ .postgres_password }}"
  data:
    - secretKey: admin_user
      remoteRef:
        key: secret/keycloak
        property: admin_user
    - secretKey: admin_password
      remoteRef:
        key: secret/keycloak
        property: admin_password
    - secretKey: postgres_password
      remoteRef:
        key: secret/keycloak
        property: postgres_password
