---
all:
  vars:
    ansible_user: sf135
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: /home/sf135/apps/homelab-ansible/keys/bootstrap-managed-hosts
    ansible_ssh_common_args: >-
      -o IdentitiesOnly=yes
      -o StrictHostKeyChecking=yes
      -o UserKnownHostsFile=/home/sf135/apps/homelab-ansible/keys/known_hosts
  children:
    gitea:
      hosts:
        sf-optiplex7000:
          ansible_host: 192.168.1.120
    vault:
      hosts:
        sf-optiplex7000:
          ansible_host: 192.168.1.120
    adguard:
      hosts:
        sf-g6:
          ansible_host: 192.168.1.118
    netdata:
      hosts:
        sf-g6:
          ansible_host: 192.168.1.118
    hermes:
      hosts:
        sf-g6:
          ansible_host: 192.168.1.118
