apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homepage.yaml
configMapGenerator:
  - name: homepage-background
    namespace: homepage
    files:
      - homelab-constellation.svg
generatorOptions:
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/component: background
