apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-local
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  diskSelector: fast
  numberOfReplicas: "1"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: medium-local
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  diskSelector: medium
  numberOfReplicas: "1"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow-local
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  diskSelector: slow
  numberOfReplicas: "1"
