apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netdata-streaming
  namespace: netdata
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netdata-streaming
    creationPolicy: Owner
    template:
      data:
        stream.conf: |
          [stream]
              enabled = yes
              destination = 192.168.1.118:19999
              api key = {{ .stream_api_key }}
  data:
    - secretKey: stream_api_key
      remoteRef:
        key: secret/netdata
        property: stream_api_key
