apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-conf-override
  namespace: netdata
data:
  netdata.conf: |
    [global]
      run as user = root
    [web]
      bind to = 0.0.0.0:19998
      default port = 19998