apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-stack-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: ssh://git@192.168.1.120:222/Homelab/homelab-iac.git
    targetRevision: main
    path: k8s/platform/ai-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
