apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storageclasses
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: ssh://git@192.168.1.120:222/Homelab/homelab-iac.git
    targetRevision: main
    path: k8s/platform/storageclasses
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
