apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-data
  namespace: ai-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: medium-local
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-data
  namespace: ai-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: medium-local
  resources:
    requests:
      storage: 2Gi
